GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "First Blog",
    "author": "Rangasai K R",
    "url": "abc.com",
    "likes": 5
}