GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blog",
  "author": "Rangasai K R",
  "url": "abc.com",
  "likes": 5
}

###
DELETE http://localhost:3003/api/blogs/617a73ce40a70f31c28f5ab9

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "anonymous",
  "name": "Anonymous",
  "password": "ansdfgg"
}