GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODI1ZDMxMjI2YzVhMDcxOTE0MWUyMSIsInVzZXJuYW1lIjoiYW5vbnltb3VzIiwiaWF0IjoxNjM2MDQzOTExfQ.dNkKVFDziOJxAEb-q_YH1aeel3t-BTOgdIfEgf1VNJU

{
  "title": "Lat Blog",
  "author": "Rangasai K R",
  "url": "abc.com",
  "user": "6182605500405cd48109c18a"
}

###
DELETE http://localhost:3003/api/blogs/617a73ce40a70f31c28f5ab9

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "anonymous",
  "name": "Anonymous",
  "password": "ansdfgg"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "anonymous",
  "password": "ansdfgg"
}